name: Automated Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run axe-core tests
        run: npm run test:axe

      - name: Upload Axe report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: axe-report
          path: dist/cdn/axe.html
          retention-days: 30

      - name: Run Vitest
        run: npm run test
